<?php
/** @var Bold_Checkout_Block_Adminhtml_System_Config_Form_Fieldset_Onboarding $this */

$onboardingBannerData = $this->getOnboardingBannerData();

if ($onboardingBannerData === null):
    return '';
endif;
?>
<div id="bold-checkout-onboarding">
    <div>
        <h2><?php echo $this->escapeHtml($onboardingBannerData['header']) ?></h2>
        <p><?php echo $this->escapeHtml($onboardingBannerData['body_text']) ?></p>
    </div>

    <button
        type="button"
        onclick="
            window.open(
                '<?php echo $this->escapeUrl($onboardingBannerData['button_link']) ?>',
                'Bold Account Center',
                'width=1400,height=950'
            )
        "
    >
        <?php echo $this->escapeHtml($onboardingBannerData['button_text']) ?>
    </button>
</div>
