<?php
/**
 * Bold Checkout Tax Exempt Information Template.
 *
 * @see Bold_CheckoutTaxExempt_Block_Info
 * @var $this Bold_CheckoutTaxExempt_Block_Info
 * @phpcs:disable
 */
?>
<?php if (!$this->isTaxExemptAllowedForOrder()) {
    return;
}
?>
<?php if (!$this->getOrder()->getCustomerId()) : ?>
    <div class="page-title title-buttons">
        <h1><?php echo $this->__('Order #%s - %s', $this->getOrder()->getRealOrderId(), $this->getOrder()->getStatusLabel()) ?></h1>
    </div>
<?php endif; ?>
<div id="tax-exempt" class='checkout-tax-exempt-section'>
    <h2 class="table-caption"><?php echo $this->__('Order Attachments '); ?></h2>
    <?php $taxExemptInfo = $this->getTaxExemptInfo(); ?>
    <?php if ($taxExemptInfo->getFile()): ?>
        <div id='tax_exempt_documents_table'>
            <table class="data-table tax-exempt-documents-table">
                <thead>
                <tr>
                    <th><?php echo $this->__('File'); ?></th>
                    <th><?php echo $this->__('Comment'); ?></th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td><a href="<?php echo $taxExemptInfo->getFileUrl(); ?>"><?php echo $taxExemptInfo->getFile(); ?></a></td>
                    <td><?php echo $this->escapeHtml($taxExemptInfo->getComment()); ?></td>
                </tr>
                </tbody>
            </table>
            <br/>
            <button id='upload_new_button' class='button' type='button'><?php echo $this->__('Upload New Document'); ?></button>
        </div>
    <?php endif; ?>
    <div id='tax_exempt_upload_form' <?php if ($taxExemptInfo->getFile()): ?>style='display:none;'<?php endif; ?>/>
    <form action="<?php echo $this->getUploadUrl(); ?>" method='post' enctype='multipart/form-data' id='tax_exempt_form'>
        <input name="public_id" type='hidden' value="<?php echo $this->getPublicOrderId(); ?>"/>
        <input name='form_key' type='hidden' value="<?php echo $this->getFormKey() ?>"/>
        <div class="form-group">
            <label for="tax_exempt_file"><?php echo $this->__('Upload Tax Exempt File (%s): ', $this->getAllowedExtensions()); ?></label>
            <input type="file" required class="input-file required" name="tax_exempt_file" id="tax_exempt_file"/>
        </div>
        <br/>
        <div class="form-group">
            <label for="tax_exempt_comment"><?php echo $this->__('Add Comment: '); ?></label>
            <textarea name="tax_exempt_comment" class='textarea' id="tax_exempt_comment" rows="2" cols="15"></textarea>
        </div>
        <br/>
        <input type="submit" class="button" value="<?php echo $this->__('Submit'); ?>"/>
        <?php if ($taxExemptInfo->getFile()): ?>
            <button id='cancel_button' class="button btn-danger" type='button'><?php echo $this->__('Cancel'); ?></button>
        <?php endif; ?>
    </form>
</div>
<br/>
<script type='text/javascript'>
    document.addEventListener('DOMContentLoaded', function () {
        var taxExemptForm = document.getElementById('tax_exempt_form');
        taxExemptForm.addEventListener('submit', function (event) {
            var taxExemptFile = document.getElementById('tax_exempt_file');
            if (!taxExemptFile.value) {
                event.preventDefault();
                alert('<?php echo $this->__('Please select a file to upload.'); ?>');
            }
        });
    });
</script>
<script type='text/javascript'>
    document.addEventListener('DOMContentLoaded', function () {
        var uploadNewButton = document.getElementById('upload_new_button');
        var cancelButton = document.getElementById('cancel_button');
        var taxExemptDocumentsTable = document.getElementById('tax_exempt_documents_table');
        var taxExemptUploadForm = document.getElementById('tax_exempt_upload_form');

        uploadNewButton.addEventListener('click', function () {
            taxExemptDocumentsTable.style.display = 'none';
            taxExemptUploadForm.style.display = 'block';
        });

        cancelButton.addEventListener('click', function () {
            taxExemptDocumentsTable.style.display = 'block';
            taxExemptUploadForm.style.display = 'none';
        });
    });
</script>
