<?php
/**
 * Bold Payments PIGI iframe template.
 *
 * @var Bold_Checkout_Block_Form_Payments $this
 */
?>
<div id="bold-payments-container" style="display: none">
    <iframe id='PIGI' scrolling='no' width="100%" frameborder='0'></iframe>
</div>
<span class='please-wait' id='bold-payments-iframe-loader' style='display:none;'>
    <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>"
         alt="<?php echo Mage::helper('core')->quoteEscape($this->__('Please wait...')) ?>"
         title="<?php echo $this->__('Please wait...') ?>"
    /> <?php echo $this->__('Please wait...') ?>
</span>

<script>
    /**
     * Bold Checkout Payment Service.
     */
    BoldPayment = Class.create({
        requestInProgress: false,
        requestQueue: [],
        jwtToken: "<?php echo $this->getJwtToken(); ?>",
        url: "<?php echo $this->getStoreFrontClientUrl(); ?>",
        iframeUrl: "<?php echo $this->escapeUrl($this->getIframeUrl()); ?>",
        /**
         * Initialize Bold Payment.
         *
         * Subscribe to PIGI iframe events, refresh Bold order to get the latest cart data, (At this point cart should already have billing address, shipping address and shipping method.)
         * and after show the PIGI iframe.
         *
         * @returns {void}
         * @public
         */
        init: function () {
            this.subscribeToPIGIEvents();
            const loader = document.querySelector('#bold-payments-iframe-loader');
            loader.style.display = 'block';
            this.request('refresh', 'GET').then(function () {
                const iframeElement = document.querySelector('iframe#PIGI');
                const boldPaymentsContainer = document.querySelector('#bold-payments-container');
                boldPaymentsContainer.style.display = 'block';
                iframeElement.src = this.iframeUrl;
                loader.style.display = 'none';
            }.bind(this)).catch(function () {
                const boldPaymentsCheckbox = document.getElementById('p_method_bold');
                boldPaymentsCheckbox.hidden = true;
            });

        },
        /**
         * Rewrite continue button onclick event to send add payment action
         * to PIGI iframe in case Bold payment method is selected.
         *
         * @returns {void}
         * @public
         */
        rewriteContinueButton: function () {
            const continueButton = document.querySelector('#payment-buttons-container .button');
            continueButton.removeAttribute('onclick');
            continueButton.addEventListener('click', function () {
                if (checkout.loadWaiting) {
                    return;
                }
                const boldPaymentsCheckbox = document.getElementById('p_method_bold');
                if (!boldPaymentsCheckbox.checked) {
                    payment.save();
                }
                checkout.setLoadWaiting('payment');
                const iframeElement = document.querySelector('iframe#PIGI');
                const iframeWindow = iframeElement.contentWindow;
                const clearAction = {actionType: 'PIGI_CLEAR_ERROR_MESSAGES'};
                const action = {actionType: 'PIGI_ADD_PAYMENT'};
                iframeWindow.postMessage(clearAction, '*');
                iframeWindow.postMessage(action, '*');
            });
        },

        /**
         * Subscribe to payment method radio buttons change event to show/hide PIGI iframe.
         *
         * @returns {void}
         * @public
         */
        updateBoldPaymentCheckbox: function () {
            const boldRadioButton = document.getElementById('p_method_bold');
            const paymentIframe = document.getElementById('PIGI');
            const paymentMethodsRadioButtons = document.querySelectorAll('input[type="radio"][name="payment[method]"]');
            boldRadioButton.checked ? paymentIframe.style.display = 'block' : paymentIframe.style.display = 'none';
            paymentMethodsRadioButtons.forEach(function (radioButton) {
                radioButton.addEventListener('change', function () {
                    const boldRadioButton = document.getElementById('p_method_bold');
                    const paymentIframe = document.getElementById('PIGI');
                    boldRadioButton.checked ? paymentIframe.style.display = 'block' : paymentIframe.style.display = 'none';
                });
            });
        },
        /**
         * Perform request to Bold Storefront API and return a Promise.
         *
         * @param {string} path
         * @param {string} method
         * @param {{}} payload
         * @returns {Promise}
         */
        request: function (path, method, payload = {}) {
            return new Promise((resolve, reject) => {
                this.requestQueue.push({path, method, payload, resolve, reject});
                this.processNextRequest();
            });
        },
        /**
         * Process next request in queue.
         *
         * Bold Storefront API allows only one request at a time.
         *
         * @returns {void}
         * @private
         */
        processNextRequest: function () {
            if (this.requestInProgress || this.requestQueue.length === 0) {
                return;
            }
            this.requestInProgress = true;
            const {path, method, payload, resolve, reject} = this.requestQueue.shift();
            new Ajax.Request(
                this.url + path,
                {
                    method: method,
                    contentType: 'application/json',
                    requestHeaders: {
                        'Authorization': 'Bearer ' + this.jwtToken,
                        'Content-Type': 'application/json',
                    },
                    parameters: payload,
                    onSuccess: (response) => {
                        resolve(response);
                        this.requestInProgress = false;
                        this.processNextRequest();
                    },
                    onFailure: (error) => {
                        reject(error);
                        this.requestInProgress = false;
                        this.processNextRequest();
                    }
                }
            );
        },
        /**
         * Subscribe to PIGI iframe events.
         */
        subscribeToPIGIEvents: function () {
            window.addEventListener('message', ({data}) => {
                const type = data.responseType;
                const iframeElement = document.querySelector('iframe#PIGI');
                if (type) {
                    switch (type) {
                        case 'PIGI_UPDATE_HEIGHT':
                            if (iframeElement.height === Math.round(data.payload.height) + 'px') {
                                return;
                            }
                            iframeElement.height = Math.round(data.payload.height) + 'px';
                            break;
                        case 'PIGI_INITIALIZED':
                            if (data.payload && data.payload.height) {
                                iframeElement.height = Math.round(data.payload.height) + 'px';
                            }
                            break;
                        case 'PIGI_REFRESH_ORDER':
                            break;
                        case 'PIGI_ADD_PAYMENT':
                            if (!data.payload.success) {
                                checkout.setLoadWaiting(false);
                                return;
                            }
                            if (!checkout.loadWaiting) {
                                checkout.setLoadWaiting('payment');
                            }
                            // Refresh Bold order to get the latest cart data before processing the order.
                            this.request('refresh', 'GET').then(function () {
                                // Need to make this request to Bold Storefront API to
                                // avoid error - "There was an error calculating the taxes" during 'process_order' request.
                                this.request('taxes', 'POST').then(function () {
                                    checkout.setLoadWaiting(false);
                                    payment.save();
                                }).catch(function () {
                                    this.displayErrorMessage('An error occurred while processing your payment. Please try again.');
                                }.bind(this));
                            }.bind(this)).catch(function () {
                                this.displayErrorMessage('An error occurred while processing your payment. Please try again.');
                            }.bind(this));
                    }
                }
            });
        },
        /**
         * Display error message in PIGI iframe.
         *
         * @private
         * @param {string} message
         */
        displayErrorMessage: function (message) {
            checkout.setLoadWaiting(false);
            const iframeElement = document.querySelector('iframe#PIGI');
            const iframeWindow = iframeElement.contentWindow;
            const action = {
                actionType: 'PIGI_DISPLAY_ERROR_MESSAGE',
                payload: {
                    error: {
                        message: message,
                        sub_type: 'string_to_categorize_error',
                    }
                }
            };
            iframeWindow.postMessage(action, '*');
        }
    });
</script>

<script>
    const boldPayment = new BoldPayment();
    boldPayment.init();
    boldPayment.rewriteContinueButton();
    boldPayment.updateBoldPaymentCheckbox();
</script>
