<?php
/**
 * Bold Payments iframe.
 *
 * @var Bold_Checkout_Block_Form_Payments $this
 */
?>
<div id="bold-payments-container">
    <iframe id='PIGI' src='' width='100%' scrolling='no' frameborder='0' style='height: 275px;'></iframe>
</div>
<script>
    document.observe('dom:loaded', function () {
        const continueButton = $('step-shipping-payment-method').down('.step-buttons-set .button.next');
        const iframeElement = $('PIGI');
        const boldPaymentsCheckbox = $('p_method_bold');
        const iframeUrl = "<?php echo $this->escapeUrl($this->getIframeUrl())?>";
        let paymentType = null;
        if (!iframeUrl || !continueButton || !boldPaymentsCheckbox) {
            const dtElements = document.getElementsByTagName('dt') || [];
            let targetElement;
            for (let i = 0; i < dtElements.length; i++) {
                if (dtElements[i].querySelector('#p_method_bold')) {
                    targetElement = dtElements[i];
                    break;
                }
            }
            if (targetElement) {
                targetElement.style.display = 'none';
            }
            return;
        }
        boldPaymentsCheckbox.checked = false;
        continueButton.stopObserving();
        continueButton.observe('click', function () {
            if (!boldPaymentsCheckbox.checked) {
                proceedToOrderOverview(this);
                return;
            }
            if (!paymentType) {
                OnecolumnCheckout.setLoadingButton(this);
                const iframeWindow = iframeElement.contentWindow;
                const clearAction = {actionType: 'PIGI_CLEAR_ERROR_MESSAGES'};
                const action = {actionType: 'PIGI_ADD_PAYMENT'};
                iframeWindow.postMessage(clearAction, '*');
                iframeWindow.postMessage(action, '*');
                return;
            }
            paymentType = null;
            proceedToOrderOverview(this);
        });
        boldPaymentsCheckbox.observe('change', function () {
            if (this.checked) {
                iframeElement.src = iframeUrl;
                const iframeWindow = iframeElement.contentWindow;
                iframeWindow.postMessage({actionType: 'PIGI_REFRESH_ORDER'}, '*');
                window.addEventListener('message', ({data}) => {
                    updateIframeHeight(data);
                    const type = data.responseType;
                    if (type) {
                        switch (type) {
                            case 'PIGI_INITIALIZED':
                                break;
                            case 'PIGI_REFRESH_ORDER':
                                break;
                            case 'PIGI_ADD_PAYMENT':
                                OnecolumnCheckout.setLoadingButton(continueButton, false);
                                if (!data.payload.success) {
                                    paymentType = null;
                                    return;
                                }
                                paymentType = data.payload.paymentType;
                                continueButton.click();
                        }
                    }
                });
            }
        });

        /**
         * Update payment iframe height.
         *
         * @private
         * @param {Object} data
         * @param data
         */
        function updateIframeHeight(data) {
            const iframeElement = $('PIGI');
            if (!data.height || iframeElement.style.height === data.height.round() + 'px') {
                return;
            }
            iframeElement.style.height = data.height.round() + 'px';
        }

        /**
         * Save payment and proceed to order overview.
         *
         * @private
         * @this {Element}
         */
        function proceedToOrderOverview(continueButton) {
            const step = continueButton.up('.step');
            const method = step.readAttribute('data-step-save');
            OnecolumnCheckout[method](
                continueButton,
                OnecolumnCheckout.stepForward.bind(OnecolumnCheckout, step.next('.step')
                )
            );
        }
    });
</script>
