<?php
/**
 * Bold Checkout Tax Exempt Information Template.
 *
 * @see Bold_CheckoutTaxExempt_Block_Adminhtml_Sales_Order_View_Tab_Attachments
 * @var $this Bold_CheckoutTaxExempt_Block_Adminhtml_Sales_Order_View_Tab_Attachments
 * @phpcs:disable
 */
?>
<div id='order_attachments'>
    <h3><?php echo $this->__('Attachments'); ?></h3>
    <?php if ($this->getTaxExemptFileName()): ?>
        <table class="data-table">
            <thead>
            <tr>
                <th><?php echo $this->__('File'); ?></th>
                <th><?php echo $this->__('Comment'); ?></th>
                <th><?php echo $this->__('Action'); ?></th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td><a href="<?php echo $this->getTaxExemptFileUrl(); ?>" target='_blank'><?php echo $this->getTaxExemptFileName(); ?></a></td>
                <td><?php echo $this->escapeHtml($this->getTaxExemptComment()); ?></td>
                <td>
                    <button class="delete-attachment" data-attachment-id="1">Remove</button>
                </td>
            </tr>
            </tbody>
        </table>
        <br/>
    <?php endif; ?>
    <form action="<?php echo $this->getUploadUrl() ?>" method="post"
          enctype="multipart/form-data" id="upload_form" class="form-list">
        <input type="hidden" name="order_id" value="<?php echo $this->getRequest()->getParam('order_id'); ?>">
        <input name='form_key' type='hidden' value="<?php echo $this->getFormKey() ?>"/>
        <div class="field">
            <label for="tax_exempt_file" class="required"><em>*</em><?php echo $this->__('Upload Tax Exempt File (%s): ', $this->getAllowedExtensions()); ?></label>
            <div class="input-box">
                <input type="file" name="tax_exempt_file" id="tax_exempt_file" class="required-entry" required>
            </div>
        </div>
        <br/>
        <div class="field">
            <label for="tax_exempt_comment"><?php echo $this->__('Comment:'); ?></label>
            <div class="input-box">
                <textarea name="tax_exempt_comment" id="tax_exempt_comment"></textarea>
            </div>
        </div>
        <div class="form-buttons">
            <button type="submit" class="scalable save" title="<?php echo $this->__('Upload'); ?>">
                <span><span><span><?php echo $this->__('Upload'); ?></span></span></span></button>
        </div>
    </form>
</div>
<script type='text/javascript'>
    document.addEventListener('DOMContentLoaded', function () {
        var deleteButtons = document.querySelectorAll('.delete-attachment');
        deleteButtons.forEach(function (deleteButton) {
            deleteButton.addEventListener('click', function (event) {
                event.preventDefault();
                if (confirm('<?php echo $this->__('Are you sure you want to delete this attachment?'); ?>')) {
                    location.href = '<?php echo $this->getDeleteUrl(); ?>';
                }
            });
        });
    });
</script>
<style>
    .data-table th,
    .data-table td {
        padding: 8px 16px;
    }
</style>
