<?php
/**
 * @var $this Bold_CheckoutIntegration_Block_Adminhtml_Form_Integrations
 */
$htmlId = $this->getHtmlId() ? $this->getHtmlId() : '_' . uniqid();
?>
<div class="grid" id="grid<?php echo $htmlId ?>">
    <table cellpadding="0" cellspacing="0" class="border">
        <tbody>
        <tr class="headings" id="headings<?php echo $htmlId ?>">
            <?php foreach ($this->_columns as $columnName => $column): ?>
                <th><?php echo $column['label'] ?></th>
            <?php endforeach; ?>
        </tr>
        <?php foreach ($this->getArrayRows() as $rowId => $row): ?>
            <tr id="<?php echo $rowId ?>">
                <?php foreach ($this->_columns as $columnName => $column): ?>
                    <td>
                        <?php echo $this->renderCellTemplate($columnName, $row) ?>
                    </td>
                <?php endforeach; ?>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>
<div id="empty<?php echo $htmlId ?>">
    <span class="grid-severity-minor">
        <span><?php echo Mage::helper('adminhtml')->__('Save the configuration to create integrations.') ?></span>
    </span>
</div>

<script type="text/javascript">
    $('empty<?php echo $htmlId ?>').hide();
    <?php if (!$this->getArrayRows()):?>
    $('grid<?php echo $htmlId ?>').hide();
    $('empty<?php echo $htmlId ?>').show();
    <?php endif;?>
</script>
